import torch

def jonker_scalar(cost: torch.Tensor) -> torch.Tensor: ...
def jonker_dense(cost: torch.Tensor) -> torch.Tensor: ...
def jonker_compact(cost: torch.Tensor) -> torch.Tensor: ...
def jonker_dense_batch(cost: torch.Tensor) -> torch.Tensor: ...
def jonker_compact_batch(cost: torch.Tensor) -> torch.Tensor: ...
def jonker_dense_batch_unpacked(
    cost: torch.Tensor,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]: ...
def jonker_compact_batch_unpacked(
    cost: torch.Tensor,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]: ...

# CUDA-only at runtime; absent on CPU-only builds.
# Typed as callable so callers don't need runtime None-checks in typed code.
def munkres(cost: torch.Tensor) -> torch.Tensor: ...
def hybrid(cost: torch.Tensor) -> torch.Tensor: ...
def lawler(cost: torch.Tensor) -> torch.Tensor: ...
def greedy(cost: torch.Tensor) -> torch.Tensor: ...
